import = ["~/.config/alacritty/themes/themes/gruvbox_dark.toml"]

[window]
padding = { x = 10, y = 10 }
dynamic_padding = true
opacity = 1.0
decorations = "buttonless"

[shell]
program = "/bin/zsh"
args = ["-l", "-c", "tmux attach || tmux"]

[font]
normal = { family = "Liga SFMono Nerd Font", style = "Regular" }
size = 16

[mouse]
hide_when_typing = false

[selection]
save_to_clipboard = true

[env]
TERM = "xterm-256color"
